sudo: required

language: rust

rust:
  - nightly

cache: cargo

services:
  - docker

script:
  - cargo test

deploy:
  provider: script
  script:
    - docker build -t frenetiq/perplexio-backend .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push frenetiq/perplexio-backend
  on:
    branch: master
