version: '3.1'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpw
    ports:
      - "5432:5432"
